# Generated by Django 3.0.5 on 2020-04-23 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitableinheritance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multitableinheritance.Place')),
                ('customers', models.ManyToManyField(related_name='provider', to='multitableinheritance.Place')),
            ],
            bases=('multitableinheritance.place',),
        ),
    ]
