# Generated by Django 3.0.5 on 2020-04-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usingmodel', '0002_runner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
