# Generated by Django 3.0.5 on 2020-04-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usingmodel', '0003_fruit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='name',
            field=models.CharField(max_length=60, verbose_name='러너이름'),
        ),
    ]
