# Generated by Django 3.0.5 on 2020-04-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makingqueries', '0002_auto_20200424_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='number_of_comments',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='number_of_pingbacks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
