# Generated by Django 3.0.5 on 2020-04-26 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makingqueries', '0003_auto_20200424_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Themeblog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='makingqueries.Blog')),
                ('theme', models.CharField(max_length=200)),
            ],
            bases=('makingqueries.blog',),
        ),
    ]
