# Generated by Django 3.0.5 on 2020-04-21 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateTimeField()),
                ('finished_date', models.DateTimeField(blank=True)),
                ('academic_record', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manytomanyexample.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manytomanyexample.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='enrolments',
            field=models.ManyToManyField(through='manytomanyexample.Enrolment', to='manytomanyexample.Student'),
        ),
    ]
