# Generated by Django 3.0.5 on 2020-04-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytomanyexample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='academic_record',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='finished_date',
            field=models.DateTimeField(null=True),
        ),
    ]
