# Generated by Django 3.0.5 on 2020-04-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetomany', '0002_car_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='car_model',
        ),
    ]
