# Generated by Django 3.0.5 on 2020-04-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstractbaseclasses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='student',
            table='student_info',
        ),
    ]
